version: '3'

services:
  app:
    image: food-web
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    # container_name: food-web
    # restart: unless-stopped